# Generated by Django 4.0.5 on 2022-06-11 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='fullname',
            field=models.CharField(default='default', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='gender',
            field=models.CharField(choices=[('male', 'male'), ('female', 'female'), ('others', 'others')], default='male', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='skills',
            field=models.CharField(default='null', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='username',
            field=models.CharField(max_length=50),
        ),
    ]
