# Generated by Django 4.0.5 on 2022-06-11 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_studentprofile_fullname_studentprofile_gender_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('skill_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('assessment_link', models.URLField()),
            ],
        ),
    ]
