# Generated by Django 4.0.5 on 2022-06-11 18:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillList',
            fields=[
                ('skill_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('assessment_link', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='RecruiterProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority1', models.CharField(max_length=50)),
                ('priority2', models.CharField(max_length=50)),
                ('priority3', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50)),
                ('bio', models.TextField(blank=True)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
