# Generated by Django 4.0.5 on 2022-06-11 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruiter', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skilllist',
            name='assessment_link',
        ),
    ]
