# Generated by Django 4.0.5 on 2022-06-11 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruiter', '0002_remove_skilllist_assessment_link'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SkillList',
        ),
    ]
